### ISSUE TITLE
Confessor Jiji / Cornifer audio bug

### ISSUE THREAD

**Issue by Ellian0** [Hallownest-Vocalized/Hallownest-Vocalized#10]
When I dreamnail Confessor Jiji, it plays a Cornifer voiceline

https://github.com/Hallownest-Vocalized/Hallownest-Vocalized/assets/137365614/e40c0a37-ef3c-4b77-b0f2-4fc8f3b43cce

**Comment by Zickles** [comment]
#9

**Comment by Zickles** [comment]
fixed in [this](https://github.com/Hallownest-Vocalized/Hallownest-Vocalized/commit/81943ad8f4f5d34f2626afaacb9f7c89b609e4ca) commit
