### ISSUE TITLE
charm vocals

### ISSUE THREAD

**Issue by godfwar** [Hallownest-Vocalized/Hallownest-Vocalized#12]
Its not an actual bug. i just find it annoying to hear the charms' descriptions. if it were an option in settings so i can deactivate it would be cool. btw thank you for the great mod i really appreciate the work<3

**Comment by Zickles** [comment]
at some point i did try to do this but it was hard to make a toggle because we have it implemented so if you toggle it off you would have to restart your game which would be pretty annoying

**Comment by Zpec7re** [comment]
Hey :v Master of Souls don't talk

**Comment by Zickles** [comment]
you mean soul master? also why in this issue?

**Comment by Zpec7re** [comment]
I mean :/ i saw in the trailer that for example Soul Master say this : "My
dreams are eternal,then so am i" .but :v i fight him and don't Say nothing
