### ISSUE TITLE
NPC Voiceline Bug

### ISSUE THREAD

**Issue by KROVP** [Hallownest-Vocalized/Hallownest-Vocalized#13]
Hello,
I downloaded all that is required for this mod to work on Scarab and the menu, charms, enemy description etc. all work except for NPC voicelines. I have noticed a couple of people who have come across the same issue in July 2023, however there is no apparent fix for it unfortunately.
Is there a way to fix this? Or is it an update issue, because I have also tried across multiple files and reinstalling the mod(s).
As a note, when I turn on the autoscroll, it does not work - from my understanding the mod itself for NPCs are not working?

**Comment by Ccmaci** [comment]
Make sure your computer's default language is set to English. If the issue persists message us in the discord
